name             'pa11y'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures pa11y'
long_description 'Installs/Configures pa11y'
version          '0.2.2'

depends 'nodejs'
depends 'mongodb'
depends 'hipsnip-mongodb'
depends 'git'
depends 'phantomjs'
