name             'pa11y'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures pa11y'
long_description 'Installs/Configures pa11y'
version          '0.1.1'

depends 'nodejs'
depends 'mongodb3', '~> 2.0.0'
depends 'git'
depends 'phantomjs'
